version: 2

# See https://golangci-lint.run/usage/configuration/ for all options

run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - misspell

formatters:
  enable:
    - gofmt
    - goimports

issues:
  exclude-use-default: false